#!/opt/local/bin/escript

main(_) ->

	ct_root_sup:start_link(),
	ct_god:init_map(),
	{ok,JoanPlayer}=ct_player_sup:start_player("joan",[]),
	ct_player:set_room(JoanPlayer,[3,3]),
	{ok,RoomPid}=ct_room_sup:get_pid([3,3]),
	{ok,RoomExits}=ct_room:get_exits(RoomPid),
	io:format("Room Exits ~w~n",[RoomExits]),
	{ok,PerePlayer}=ct_player_sup:start_player("pere",[]),
	ct_player:set_room(PerePlayer,[3,3]),
	timer:sleep(1000),
	ct_player:go(JoanPlayer,s),
	timer:sleep(2000).